ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "vatNumber" TEXT;
ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "gstProofUrl" TEXT;
ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "termsAcceptedAt" TIMESTAMP(3);
